// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/v1/magicbox.proto

package magicboxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MagicboxOS_SendWebhook_FullMethodName       = "/magicbox.v1.MagicboxOS/SendWebhook"
	MagicboxOS_GetProfile_FullMethodName        = "/magicbox.v1.MagicboxOS/GetProfile"
	MagicboxOS_ListSharedVolumes_FullMethodName = "/magicbox.v1.MagicboxOS/ListSharedVolumes"
)

// MagicboxOSClient is the client API for MagicboxOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MagicboxOS is the gRPC API exposed to installed app containers.
// Apps authenticate using the MAGICBOX_API_TOKEN JWT injected as an env var.
// The token encodes the user_id, app_id, and granted scopes.
//
// File I/O (shared volumes, app_state, transit) is handled via direct
// Docker volume mounts — no gRPC needed for filesystem operations.
type MagicboxOSClient interface {
	// SendWebhook dispatches a payload to another app's webhook endpoint.
	// This is the only way for apps to communicate since inter-container
	// communication (ICC) is disabled on the magicbox_net network.
	SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error)
	// GetProfile returns the owning user's profile information.
	// Requires scope: profile:read
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// ListSharedVolumes returns the shared volumes accessible to the calling app,
	// derived from the app's granted scopes. Useful for runtime discovery.
	ListSharedVolumes(ctx context.Context, in *ListSharedVolumesRequest, opts ...grpc.CallOption) (*ListSharedVolumesResponse, error)
}

type magicboxOSClient struct {
	cc grpc.ClientConnInterface
}

func NewMagicboxOSClient(cc grpc.ClientConnInterface) MagicboxOSClient {
	return &magicboxOSClient{cc}
}

func (c *magicboxOSClient) SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWebhookResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_SendWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) ListSharedVolumes(ctx context.Context, in *ListSharedVolumesRequest, opts ...grpc.CallOption) (*ListSharedVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedVolumesResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_ListSharedVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagicboxOSServer is the server API for MagicboxOS service.
// All implementations must embed UnimplementedMagicboxOSServer
// for forward compatibility.
//
// MagicboxOS is the gRPC API exposed to installed app containers.
// Apps authenticate using the MAGICBOX_API_TOKEN JWT injected as an env var.
// The token encodes the user_id, app_id, and granted scopes.
//
// File I/O (shared volumes, app_state, transit) is handled via direct
// Docker volume mounts — no gRPC needed for filesystem operations.
type MagicboxOSServer interface {
	// SendWebhook dispatches a payload to another app's webhook endpoint.
	// This is the only way for apps to communicate since inter-container
	// communication (ICC) is disabled on the magicbox_net network.
	SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error)
	// GetProfile returns the owning user's profile information.
	// Requires scope: profile:read
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// ListSharedVolumes returns the shared volumes accessible to the calling app,
	// derived from the app's granted scopes. Useful for runtime discovery.
	ListSharedVolumes(context.Context, *ListSharedVolumesRequest) (*ListSharedVolumesResponse, error)
	mustEmbedUnimplementedMagicboxOSServer()
}

// UnimplementedMagicboxOSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagicboxOSServer struct{}

func (UnimplementedMagicboxOSServer) SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebhook not implemented")
}
func (UnimplementedMagicboxOSServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedMagicboxOSServer) ListSharedVolumes(context.Context, *ListSharedVolumesRequest) (*ListSharedVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedVolumes not implemented")
}
func (UnimplementedMagicboxOSServer) mustEmbedUnimplementedMagicboxOSServer() {}
func (UnimplementedMagicboxOSServer) testEmbeddedByValue()                    {}

// UnsafeMagicboxOSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagicboxOSServer will
// result in compilation errors.
type UnsafeMagicboxOSServer interface {
	mustEmbedUnimplementedMagicboxOSServer()
}

func RegisterMagicboxOSServer(s grpc.ServiceRegistrar, srv MagicboxOSServer) {
	// If the following call panics, it indicates UnimplementedMagicboxOSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MagicboxOS_ServiceDesc, srv)
}

func _MagicboxOS_SendWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).SendWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_SendWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).SendWebhook(ctx, req.(*SendWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_ListSharedVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).ListSharedVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_ListSharedVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).ListSharedVolumes(ctx, req.(*ListSharedVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MagicboxOS_ServiceDesc is the grpc.ServiceDesc for MagicboxOS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MagicboxOS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "magicbox.v1.MagicboxOS",
	HandlerType: (*MagicboxOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWebhook",
			Handler:    _MagicboxOS_SendWebhook_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _MagicboxOS_GetProfile_Handler,
		},
		{
			MethodName: "ListSharedVolumes",
			Handler:    _MagicboxOS_ListSharedVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/magicbox.proto",
}
