// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/v1/magicbox.proto

package magicboxpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MagicboxOS_SendWebhook_FullMethodName        = "/magicbox.v1.MagicboxOS/SendWebhook"
	MagicboxOS_GetProfile_FullMethodName         = "/magicbox.v1.MagicboxOS/GetProfile"
	MagicboxOS_ListSharedVolumes_FullMethodName  = "/magicbox.v1.MagicboxOS/ListSharedVolumes"
	MagicboxOS_SendToContact_FullMethodName      = "/magicbox.v1.MagicboxOS/SendToContact"
	MagicboxOS_ListContacts_FullMethodName       = "/magicbox.v1.MagicboxOS/ListContacts"
	MagicboxOS_GetInviteLink_FullMethodName      = "/magicbox.v1.MagicboxOS/GetInviteLink"
	MagicboxOS_SendContactRequest_FullMethodName = "/magicbox.v1.MagicboxOS/SendContactRequest"
	MagicboxOS_RequestPermissions_FullMethodName = "/magicbox.v1.MagicboxOS/RequestPermissions"
	MagicboxOS_HasScopes_FullMethodName          = "/magicbox.v1.MagicboxOS/HasScopes"
)

// MagicboxOSClient is the client API for MagicboxOS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MagicboxOS is the gRPC API exposed to installed app containers.
// Apps authenticate using the MAGICBOX_API_TOKEN JWT injected as an env var.
// The token encodes the user_id, app_id, and granted scopes.
//
// File I/O (shared volumes, app_state, transit) is handled via direct
// Docker volume mounts — no gRPC needed for filesystem operations.
type MagicboxOSClient interface {
	// SendWebhook dispatches a payload to another app's webhook endpoint.
	// This is the only way for apps to communicate since inter-container
	// communication (ICC) is disabled on the magicbox_net network.
	SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error)
	// GetProfile returns the owning user's profile information.
	// Requires scope: profile:read
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	// ListSharedVolumes returns the shared volumes accessible to the calling app,
	// derived from the app's granted scopes. Useful for runtime discovery.
	ListSharedVolumes(ctx context.Context, in *ListSharedVolumesRequest, opts ...grpc.CallOption) (*ListSharedVolumesResponse, error)
	// SendToContact signs and encrypts a message at the transport layer,
	// then dispatches it directly to a federated contact over the libp2p network.
	SendToContact(ctx context.Context, in *SendToContactRequest, opts ...grpc.CallOption) (*SendToContactResponse, error)
	// ListContacts returns the owning user's contact list.
	// Requires scope: contacts:read
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	// GetInviteLink returns the current user's invite link for contact sharing.
	// Requires scope: contacts:read
	GetInviteLink(ctx context.Context, in *GetInviteLinkRequest, opts ...grpc.CallOption) (*GetInviteLinkResponse, error)
	// SendContactRequest sends a contact request to a remote user via their invite link.
	// Requires scope: contacts:write
	SendContactRequest(ctx context.Context, in *SendContactRequestRequest, opts ...grpc.CallOption) (*SendContactRequestResponse, error)
	// RequestPermissions asks the user dynamically for new permission scopes.
	RequestPermissions(ctx context.Context, in *RequestPermissionsRequest, opts ...grpc.CallOption) (*RequestPermissionsResponse, error)
	// HasScopes checks if the calling app is already granted a set of scopes.
	HasScopes(ctx context.Context, in *HasScopesRequest, opts ...grpc.CallOption) (*HasScopesResponse, error)
}

type magicboxOSClient struct {
	cc grpc.ClientConnInterface
}

func NewMagicboxOSClient(cc grpc.ClientConnInterface) MagicboxOSClient {
	return &magicboxOSClient{cc}
}

func (c *magicboxOSClient) SendWebhook(ctx context.Context, in *SendWebhookRequest, opts ...grpc.CallOption) (*SendWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWebhookResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_SendWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) ListSharedVolumes(ctx context.Context, in *ListSharedVolumesRequest, opts ...grpc.CallOption) (*ListSharedVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSharedVolumesResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_ListSharedVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) SendToContact(ctx context.Context, in *SendToContactRequest, opts ...grpc.CallOption) (*SendToContactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendToContactResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_SendToContact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_ListContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) GetInviteLink(ctx context.Context, in *GetInviteLinkRequest, opts ...grpc.CallOption) (*GetInviteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteLinkResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_GetInviteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) SendContactRequest(ctx context.Context, in *SendContactRequestRequest, opts ...grpc.CallOption) (*SendContactRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendContactRequestResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_SendContactRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) RequestPermissions(ctx context.Context, in *RequestPermissionsRequest, opts ...grpc.CallOption) (*RequestPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPermissionsResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_RequestPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magicboxOSClient) HasScopes(ctx context.Context, in *HasScopesRequest, opts ...grpc.CallOption) (*HasScopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasScopesResponse)
	err := c.cc.Invoke(ctx, MagicboxOS_HasScopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagicboxOSServer is the server API for MagicboxOS service.
// All implementations must embed UnimplementedMagicboxOSServer
// for forward compatibility.
//
// MagicboxOS is the gRPC API exposed to installed app containers.
// Apps authenticate using the MAGICBOX_API_TOKEN JWT injected as an env var.
// The token encodes the user_id, app_id, and granted scopes.
//
// File I/O (shared volumes, app_state, transit) is handled via direct
// Docker volume mounts — no gRPC needed for filesystem operations.
type MagicboxOSServer interface {
	// SendWebhook dispatches a payload to another app's webhook endpoint.
	// This is the only way for apps to communicate since inter-container
	// communication (ICC) is disabled on the magicbox_net network.
	SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error)
	// GetProfile returns the owning user's profile information.
	// Requires scope: profile:read
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// ListSharedVolumes returns the shared volumes accessible to the calling app,
	// derived from the app's granted scopes. Useful for runtime discovery.
	ListSharedVolumes(context.Context, *ListSharedVolumesRequest) (*ListSharedVolumesResponse, error)
	// SendToContact signs and encrypts a message at the transport layer,
	// then dispatches it directly to a federated contact over the libp2p network.
	SendToContact(context.Context, *SendToContactRequest) (*SendToContactResponse, error)
	// ListContacts returns the owning user's contact list.
	// Requires scope: contacts:read
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	// GetInviteLink returns the current user's invite link for contact sharing.
	// Requires scope: contacts:read
	GetInviteLink(context.Context, *GetInviteLinkRequest) (*GetInviteLinkResponse, error)
	// SendContactRequest sends a contact request to a remote user via their invite link.
	// Requires scope: contacts:write
	SendContactRequest(context.Context, *SendContactRequestRequest) (*SendContactRequestResponse, error)
	// RequestPermissions asks the user dynamically for new permission scopes.
	RequestPermissions(context.Context, *RequestPermissionsRequest) (*RequestPermissionsResponse, error)
	// HasScopes checks if the calling app is already granted a set of scopes.
	HasScopes(context.Context, *HasScopesRequest) (*HasScopesResponse, error)
	mustEmbedUnimplementedMagicboxOSServer()
}

// UnimplementedMagicboxOSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagicboxOSServer struct{}

func (UnimplementedMagicboxOSServer) SendWebhook(context.Context, *SendWebhookRequest) (*SendWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWebhook not implemented")
}
func (UnimplementedMagicboxOSServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedMagicboxOSServer) ListSharedVolumes(context.Context, *ListSharedVolumesRequest) (*ListSharedVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSharedVolumes not implemented")
}
func (UnimplementedMagicboxOSServer) SendToContact(context.Context, *SendToContactRequest) (*SendToContactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToContact not implemented")
}
func (UnimplementedMagicboxOSServer) ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContacts not implemented")
}
func (UnimplementedMagicboxOSServer) GetInviteLink(context.Context, *GetInviteLinkRequest) (*GetInviteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInviteLink not implemented")
}
func (UnimplementedMagicboxOSServer) SendContactRequest(context.Context, *SendContactRequestRequest) (*SendContactRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendContactRequest not implemented")
}
func (UnimplementedMagicboxOSServer) RequestPermissions(context.Context, *RequestPermissionsRequest) (*RequestPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPermissions not implemented")
}
func (UnimplementedMagicboxOSServer) HasScopes(context.Context, *HasScopesRequest) (*HasScopesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasScopes not implemented")
}
func (UnimplementedMagicboxOSServer) mustEmbedUnimplementedMagicboxOSServer() {}
func (UnimplementedMagicboxOSServer) testEmbeddedByValue()                    {}

// UnsafeMagicboxOSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagicboxOSServer will
// result in compilation errors.
type UnsafeMagicboxOSServer interface {
	mustEmbedUnimplementedMagicboxOSServer()
}

func RegisterMagicboxOSServer(s grpc.ServiceRegistrar, srv MagicboxOSServer) {
	// If the following call panics, it indicates UnimplementedMagicboxOSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MagicboxOS_ServiceDesc, srv)
}

func _MagicboxOS_SendWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).SendWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_SendWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).SendWebhook(ctx, req.(*SendWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_ListSharedVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSharedVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).ListSharedVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_ListSharedVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).ListSharedVolumes(ctx, req.(*ListSharedVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_SendToContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).SendToContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_SendToContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).SendToContact(ctx, req.(*SendToContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_ListContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_GetInviteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).GetInviteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_GetInviteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).GetInviteLink(ctx, req.(*GetInviteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_SendContactRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendContactRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).SendContactRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_SendContactRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).SendContactRequest(ctx, req.(*SendContactRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_RequestPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).RequestPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_RequestPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).RequestPermissions(ctx, req.(*RequestPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagicboxOS_HasScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicboxOSServer).HasScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagicboxOS_HasScopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicboxOSServer).HasScopes(ctx, req.(*HasScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MagicboxOS_ServiceDesc is the grpc.ServiceDesc for MagicboxOS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MagicboxOS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "magicbox.v1.MagicboxOS",
	HandlerType: (*MagicboxOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWebhook",
			Handler:    _MagicboxOS_SendWebhook_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _MagicboxOS_GetProfile_Handler,
		},
		{
			MethodName: "ListSharedVolumes",
			Handler:    _MagicboxOS_ListSharedVolumes_Handler,
		},
		{
			MethodName: "SendToContact",
			Handler:    _MagicboxOS_SendToContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _MagicboxOS_ListContacts_Handler,
		},
		{
			MethodName: "GetInviteLink",
			Handler:    _MagicboxOS_GetInviteLink_Handler,
		},
		{
			MethodName: "SendContactRequest",
			Handler:    _MagicboxOS_SendContactRequest_Handler,
		},
		{
			MethodName: "RequestPermissions",
			Handler:    _MagicboxOS_RequestPermissions_Handler,
		},
		{
			MethodName: "HasScopes",
			Handler:    _MagicboxOS_HasScopes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/magicbox.proto",
}
