// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/magicbox.proto

package magicboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasScopesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scopes        []string               `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasScopesRequest) Reset() {
	*x = HasScopesRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasScopesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasScopesRequest) ProtoMessage() {}

func (x *HasScopesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasScopesRequest.ProtoReflect.Descriptor instead.
func (*HasScopesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{0}
}

func (x *HasScopesRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type HasScopesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAll        bool                   `protobuf:"varint,1,opt,name=has_all,json=hasAll,proto3" json:"has_all,omitempty"`
	MissingScopes []string               `protobuf:"bytes,2,rep,name=missing_scopes,json=missingScopes,proto3" json:"missing_scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasScopesResponse) Reset() {
	*x = HasScopesResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasScopesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasScopesResponse) ProtoMessage() {}

func (x *HasScopesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasScopesResponse.ProtoReflect.Descriptor instead.
func (*HasScopesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{1}
}

func (x *HasScopesResponse) GetHasAll() bool {
	if x != nil {
		return x.HasAll
	}
	return false
}

func (x *HasScopesResponse) GetMissingScopes() []string {
	if x != nil {
		return x.MissingScopes
	}
	return nil
}

type ScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeRequest) Reset() {
	*x = ScopeRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeRequest) ProtoMessage() {}

func (x *ScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeRequest.ProtoReflect.Descriptor instead.
func (*ScopeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{2}
}

func (x *ScopeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ScopeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RequestPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ScopeRequest        `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPermissionsRequest) Reset() {
	*x = RequestPermissionsRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPermissionsRequest) ProtoMessage() {}

func (x *RequestPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPermissionsRequest.ProtoReflect.Descriptor instead.
func (*RequestPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPermissionsRequest) GetRequests() []*ScopeRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RequestPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	NewAppToken   string                 `protobuf:"bytes,2,opt,name=new_app_token,json=newAppToken,proto3" json:"new_app_token,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPermissionsResponse) Reset() {
	*x = RequestPermissionsResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPermissionsResponse) ProtoMessage() {}

func (x *RequestPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPermissionsResponse.ProtoReflect.Descriptor instead.
func (*RequestPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{4}
}

func (x *RequestPermissionsResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RequestPermissionsResponse) GetNewAppToken() string {
	if x != nil {
		return x.NewAppToken
	}
	return ""
}

func (x *RequestPermissionsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SendWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The app_id of the target app (e.g. "com.magicbox.drive").
	TargetAppId string `protobuf:"bytes,1,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	// The user_id who owns the target app instance.
	TargetUserId string `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	// Arbitrary payload delivered to the target's webhook endpoint.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebhookRequest) Reset() {
	*x = SendWebhookRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookRequest) ProtoMessage() {}

func (x *SendWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookRequest.ProtoReflect.Descriptor instead.
func (*SendWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{5}
}

func (x *SendWebhookRequest) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *SendWebhookRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SendWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code returned by the target app's webhook handler.
	HttpStatus    int32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebhookResponse) Reset() {
	*x = SendWebhookResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookResponse) ProtoMessage() {}

func (x *SendWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookResponse.ProtoReflect.Descriptor instead.
func (*SendWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{6}
}

func (x *SendWebhookResponse) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{7}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListSharedVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharedVolumesRequest) Reset() {
	*x = ListSharedVolumesRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedVolumesRequest) ProtoMessage() {}

func (x *ListSharedVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListSharedVolumesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{9}
}

type ListSharedVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*SharedVolume        `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharedVolumesResponse) Reset() {
	*x = ListSharedVolumesResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedVolumesResponse) ProtoMessage() {}

func (x *ListSharedVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListSharedVolumesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{10}
}

func (x *ListSharedVolumesResponse) GetVolumes() []*SharedVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type SharedVolume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "ro" or "rw"
	Access        string `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedVolume) Reset() {
	*x = SharedVolume{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedVolume) ProtoMessage() {}

func (x *SharedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedVolume.ProtoReflect.Descriptor instead.
func (*SharedVolume) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{11}
}

func (x *SharedVolume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SharedVolume) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type SendToContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToContactRequest) Reset() {
	*x = SendToContactRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToContactRequest) ProtoMessage() {}

func (x *SendToContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToContactRequest.ProtoReflect.Descriptor instead.
func (*SendToContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{12}
}

func (x *SendToContactRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *SendToContactRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SendToContactRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToContactResponse) Reset() {
	*x = SendToContactResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToContactResponse) ProtoMessage() {}

func (x *SendToContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToContactResponse.ProtoReflect.Descriptor instead.
func (*SendToContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{13}
}

func (x *SendToContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendToContactResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{14}
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{15}
}

func (x *ListContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type Contact struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Multiaddr    string                 `protobuf:"bytes,3,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	TargetUserId string                 `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	// Pre-computed invite link for this contact, built from their stored identity.
	InviteLink    string `protobuf:"bytes,5,opt,name=invite_link,json=inviteLink,proto3" json:"invite_link,omitempty"`
	Status        string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{16}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Contact) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

func (x *Contact) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *Contact) GetInviteLink() string {
	if x != nil {
		return x.InviteLink
	}
	return ""
}

func (x *Contact) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetInviteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteLinkRequest) Reset() {
	*x = GetInviteLinkRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteLinkRequest) ProtoMessage() {}

func (x *GetInviteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteLinkRequest.ProtoReflect.Descriptor instead.
func (*GetInviteLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{17}
}

type GetInviteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteLink    string                 `protobuf:"bytes,1,opt,name=invite_link,json=inviteLink,proto3" json:"invite_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteLinkResponse) Reset() {
	*x = GetInviteLinkResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteLinkResponse) ProtoMessage() {}

func (x *GetInviteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteLinkResponse.ProtoReflect.Descriptor instead.
func (*GetInviteLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{18}
}

func (x *GetInviteLinkResponse) GetInviteLink() string {
	if x != nil {
		return x.InviteLink
	}
	return ""
}

type SendContactRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteLink    string                 `protobuf:"bytes,1,opt,name=invite_link,json=inviteLink,proto3" json:"invite_link,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendContactRequestRequest) Reset() {
	*x = SendContactRequestRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendContactRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContactRequestRequest) ProtoMessage() {}

func (x *SendContactRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContactRequestRequest.ProtoReflect.Descriptor instead.
func (*SendContactRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{19}
}

func (x *SendContactRequestRequest) GetInviteLink() string {
	if x != nil {
		return x.InviteLink
	}
	return ""
}

func (x *SendContactRequestRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type SendContactRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendContactRequestResponse) Reset() {
	*x = SendContactRequestResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendContactRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContactRequestResponse) ProtoMessage() {}

func (x *SendContactRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContactRequestResponse.ProtoReflect.Descriptor instead.
func (*SendContactRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{20}
}

func (x *SendContactRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendContactRequestResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_api_proto_v1_magicbox_proto protoreflect.FileDescriptor

const file_api_proto_v1_magicbox_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/magicbox.proto\x12\vmagicbox.v1\"*\n" +
	"\x10HasScopesRequest\x12\x16\n" +
	"\x06scopes\x18\x01 \x03(\tR\x06scopes\"S\n" +
	"\x11HasScopesResponse\x12\x17\n" +
	"\ahas_all\x18\x01 \x01(\bR\x06hasAll\x12%\n" +
	"\x0emissing_scopes\x18\x02 \x03(\tR\rmissingScopes\"<\n" +
	"\fScopeRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"R\n" +
	"\x19RequestPermissionsRequest\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.magicbox.v1.ScopeRequestR\brequests\"y\n" +
	"\x1aRequestPermissionsResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\"\n" +
	"\rnew_app_token\x18\x02 \x01(\tR\vnewAppToken\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"x\n" +
	"\x12SendWebhookRequest\x12\"\n" +
	"\rtarget_app_id\x18\x01 \x01(\tR\vtargetAppId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"6\n" +
	"\x13SendWebhookResponse\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x05R\n" +
	"httpStatus\"\x13\n" +
	"\x11GetProfileRequest\"h\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x1a\n" +
	"\x18ListSharedVolumesRequest\"P\n" +
	"\x19ListSharedVolumesResponse\x123\n" +
	"\avolumes\x18\x01 \x03(\v2\x19.magicbox.v1.SharedVolumeR\avolumes\":\n" +
	"\fSharedVolume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06access\x18\x02 \x01(\tR\x06access\"f\n" +
	"\x14SendToContactRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"X\n" +
	"\x15SendToContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\x15\n" +
	"\x13ListContactsRequest\"H\n" +
	"\x14ListContactsResponse\x120\n" +
	"\bcontacts\x18\x01 \x03(\v2\x14.magicbox.v1.ContactR\bcontacts\"\xb9\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tmultiaddr\x18\x03 \x01(\tR\tmultiaddr\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12\x1f\n" +
	"\vinvite_link\x18\x05 \x01(\tR\n" +
	"inviteLink\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x16\n" +
	"\x14GetInviteLinkRequest\"8\n" +
	"\x15GetInviteLinkResponse\x12\x1f\n" +
	"\vinvite_link\x18\x01 \x01(\tR\n" +
	"inviteLink\"_\n" +
	"\x19SendContactRequestRequest\x12\x1f\n" +
	"\vinvite_link\x18\x01 \x01(\tR\n" +
	"inviteLink\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"]\n" +
	"\x1aSendContactRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage2\xb0\x06\n" +
	"\n" +
	"MagicboxOS\x12P\n" +
	"\vSendWebhook\x12\x1f.magicbox.v1.SendWebhookRequest\x1a .magicbox.v1.SendWebhookResponse\x12M\n" +
	"\n" +
	"GetProfile\x12\x1e.magicbox.v1.GetProfileRequest\x1a\x1f.magicbox.v1.GetProfileResponse\x12b\n" +
	"\x11ListSharedVolumes\x12%.magicbox.v1.ListSharedVolumesRequest\x1a&.magicbox.v1.ListSharedVolumesResponse\x12V\n" +
	"\rSendToContact\x12!.magicbox.v1.SendToContactRequest\x1a\".magicbox.v1.SendToContactResponse\x12S\n" +
	"\fListContacts\x12 .magicbox.v1.ListContactsRequest\x1a!.magicbox.v1.ListContactsResponse\x12V\n" +
	"\rGetInviteLink\x12!.magicbox.v1.GetInviteLinkRequest\x1a\".magicbox.v1.GetInviteLinkResponse\x12e\n" +
	"\x12SendContactRequest\x12&.magicbox.v1.SendContactRequestRequest\x1a'.magicbox.v1.SendContactRequestResponse\x12e\n" +
	"\x12RequestPermissions\x12&.magicbox.v1.RequestPermissionsRequest\x1a'.magicbox.v1.RequestPermissionsResponse\x12J\n" +
	"\tHasScopes\x12\x1d.magicbox.v1.HasScopesRequest\x1a\x1e.magicbox.v1.HasScopesResponseB2Z0github.com/magicbox/core/api/proto/v1;magicboxpbb\x06proto3"

var (
	file_api_proto_v1_magicbox_proto_rawDescOnce sync.Once
	file_api_proto_v1_magicbox_proto_rawDescData []byte
)

func file_api_proto_v1_magicbox_proto_rawDescGZIP() []byte {
	file_api_proto_v1_magicbox_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_magicbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_magicbox_proto_rawDesc), len(file_api_proto_v1_magicbox_proto_rawDesc)))
	})
	return file_api_proto_v1_magicbox_proto_rawDescData
}

var file_api_proto_v1_magicbox_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_v1_magicbox_proto_goTypes = []any{
	(*HasScopesRequest)(nil),           // 0: magicbox.v1.HasScopesRequest
	(*HasScopesResponse)(nil),          // 1: magicbox.v1.HasScopesResponse
	(*ScopeRequest)(nil),               // 2: magicbox.v1.ScopeRequest
	(*RequestPermissionsRequest)(nil),  // 3: magicbox.v1.RequestPermissionsRequest
	(*RequestPermissionsResponse)(nil), // 4: magicbox.v1.RequestPermissionsResponse
	(*SendWebhookRequest)(nil),         // 5: magicbox.v1.SendWebhookRequest
	(*SendWebhookResponse)(nil),        // 6: magicbox.v1.SendWebhookResponse
	(*GetProfileRequest)(nil),          // 7: magicbox.v1.GetProfileRequest
	(*GetProfileResponse)(nil),         // 8: magicbox.v1.GetProfileResponse
	(*ListSharedVolumesRequest)(nil),   // 9: magicbox.v1.ListSharedVolumesRequest
	(*ListSharedVolumesResponse)(nil),  // 10: magicbox.v1.ListSharedVolumesResponse
	(*SharedVolume)(nil),               // 11: magicbox.v1.SharedVolume
	(*SendToContactRequest)(nil),       // 12: magicbox.v1.SendToContactRequest
	(*SendToContactResponse)(nil),      // 13: magicbox.v1.SendToContactResponse
	(*ListContactsRequest)(nil),        // 14: magicbox.v1.ListContactsRequest
	(*ListContactsResponse)(nil),       // 15: magicbox.v1.ListContactsResponse
	(*Contact)(nil),                    // 16: magicbox.v1.Contact
	(*GetInviteLinkRequest)(nil),       // 17: magicbox.v1.GetInviteLinkRequest
	(*GetInviteLinkResponse)(nil),      // 18: magicbox.v1.GetInviteLinkResponse
	(*SendContactRequestRequest)(nil),  // 19: magicbox.v1.SendContactRequestRequest
	(*SendContactRequestResponse)(nil), // 20: magicbox.v1.SendContactRequestResponse
}
var file_api_proto_v1_magicbox_proto_depIdxs = []int32{
	2,  // 0: magicbox.v1.RequestPermissionsRequest.requests:type_name -> magicbox.v1.ScopeRequest
	11, // 1: magicbox.v1.ListSharedVolumesResponse.volumes:type_name -> magicbox.v1.SharedVolume
	16, // 2: magicbox.v1.ListContactsResponse.contacts:type_name -> magicbox.v1.Contact
	5,  // 3: magicbox.v1.MagicboxOS.SendWebhook:input_type -> magicbox.v1.SendWebhookRequest
	7,  // 4: magicbox.v1.MagicboxOS.GetProfile:input_type -> magicbox.v1.GetProfileRequest
	9,  // 5: magicbox.v1.MagicboxOS.ListSharedVolumes:input_type -> magicbox.v1.ListSharedVolumesRequest
	12, // 6: magicbox.v1.MagicboxOS.SendToContact:input_type -> magicbox.v1.SendToContactRequest
	14, // 7: magicbox.v1.MagicboxOS.ListContacts:input_type -> magicbox.v1.ListContactsRequest
	17, // 8: magicbox.v1.MagicboxOS.GetInviteLink:input_type -> magicbox.v1.GetInviteLinkRequest
	19, // 9: magicbox.v1.MagicboxOS.SendContactRequest:input_type -> magicbox.v1.SendContactRequestRequest
	3,  // 10: magicbox.v1.MagicboxOS.RequestPermissions:input_type -> magicbox.v1.RequestPermissionsRequest
	0,  // 11: magicbox.v1.MagicboxOS.HasScopes:input_type -> magicbox.v1.HasScopesRequest
	6,  // 12: magicbox.v1.MagicboxOS.SendWebhook:output_type -> magicbox.v1.SendWebhookResponse
	8,  // 13: magicbox.v1.MagicboxOS.GetProfile:output_type -> magicbox.v1.GetProfileResponse
	10, // 14: magicbox.v1.MagicboxOS.ListSharedVolumes:output_type -> magicbox.v1.ListSharedVolumesResponse
	13, // 15: magicbox.v1.MagicboxOS.SendToContact:output_type -> magicbox.v1.SendToContactResponse
	15, // 16: magicbox.v1.MagicboxOS.ListContacts:output_type -> magicbox.v1.ListContactsResponse
	18, // 17: magicbox.v1.MagicboxOS.GetInviteLink:output_type -> magicbox.v1.GetInviteLinkResponse
	20, // 18: magicbox.v1.MagicboxOS.SendContactRequest:output_type -> magicbox.v1.SendContactRequestResponse
	4,  // 19: magicbox.v1.MagicboxOS.RequestPermissions:output_type -> magicbox.v1.RequestPermissionsResponse
	1,  // 20: magicbox.v1.MagicboxOS.HasScopes:output_type -> magicbox.v1.HasScopesResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_magicbox_proto_init() }
func file_api_proto_v1_magicbox_proto_init() {
	if File_api_proto_v1_magicbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_magicbox_proto_rawDesc), len(file_api_proto_v1_magicbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_magicbox_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_magicbox_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_magicbox_proto_msgTypes,
	}.Build()
	File_api_proto_v1_magicbox_proto = out.File
	file_api_proto_v1_magicbox_proto_goTypes = nil
	file_api_proto_v1_magicbox_proto_depIdxs = nil
}
