// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/magicbox.proto

package magicboxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The app_id of the target app (e.g. "com.magicbox.drive").
	TargetAppId string `protobuf:"bytes,1,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	// The user_id who owns the target app instance.
	TargetUserId string `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	// Arbitrary payload delivered to the target's webhook endpoint.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebhookRequest) Reset() {
	*x = SendWebhookRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookRequest) ProtoMessage() {}

func (x *SendWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookRequest.ProtoReflect.Descriptor instead.
func (*SendWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{0}
}

func (x *SendWebhookRequest) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *SendWebhookRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SendWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code returned by the target app's webhook handler.
	HttpStatus    int32 `protobuf:"varint,1,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWebhookResponse) Reset() {
	*x = SendWebhookResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWebhookResponse) ProtoMessage() {}

func (x *SendWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWebhookResponse.ProtoReflect.Descriptor instead.
func (*SendWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{1}
}

func (x *SendWebhookResponse) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{2}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListSharedVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharedVolumesRequest) Reset() {
	*x = ListSharedVolumesRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedVolumesRequest) ProtoMessage() {}

func (x *ListSharedVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListSharedVolumesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{4}
}

type ListSharedVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*SharedVolume        `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSharedVolumesResponse) Reset() {
	*x = ListSharedVolumesResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSharedVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSharedVolumesResponse) ProtoMessage() {}

func (x *ListSharedVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSharedVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListSharedVolumesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListSharedVolumesResponse) GetVolumes() []*SharedVolume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type SharedVolume struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "ro" or "rw"
	Access        string `protobuf:"bytes,2,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedVolume) Reset() {
	*x = SharedVolume{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedVolume) ProtoMessage() {}

func (x *SharedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedVolume.ProtoReflect.Descriptor instead.
func (*SharedVolume) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{6}
}

func (x *SharedVolume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SharedVolume) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type SendToContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToContactRequest) Reset() {
	*x = SendToContactRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToContactRequest) ProtoMessage() {}

func (x *SendToContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToContactRequest.ProtoReflect.Descriptor instead.
func (*SendToContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{7}
}

func (x *SendToContactRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *SendToContactRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SendToContactRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendToContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToContactResponse) Reset() {
	*x = SendToContactResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToContactResponse) ProtoMessage() {}

func (x *SendToContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToContactResponse.ProtoReflect.Descriptor instead.
func (*SendToContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{8}
}

func (x *SendToContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendToContactResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

type ListContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsRequest) Reset() {
	*x = ListContactsRequest{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsRequest) ProtoMessage() {}

func (x *ListContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsRequest.ProtoReflect.Descriptor instead.
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{9}
}

type ListContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsResponse) Reset() {
	*x = ListContactsResponse{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsResponse) ProtoMessage() {}

func (x *ListContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsResponse.ProtoReflect.Descriptor instead.
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{10}
}

func (x *ListContactsResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Multiaddr     string                 `protobuf:"bytes,3,opt,name=multiaddr,proto3" json:"multiaddr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_magicbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_magicbox_proto_rawDescGZIP(), []int{11}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Contact) GetMultiaddr() string {
	if x != nil {
		return x.Multiaddr
	}
	return ""
}

var File_api_proto_v1_magicbox_proto protoreflect.FileDescriptor

const file_api_proto_v1_magicbox_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/magicbox.proto\x12\vmagicbox.v1\"x\n" +
	"\x12SendWebhookRequest\x12\"\n" +
	"\rtarget_app_id\x18\x01 \x01(\tR\vtargetAppId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"6\n" +
	"\x13SendWebhookResponse\x12\x1f\n" +
	"\vhttp_status\x18\x01 \x01(\x05R\n" +
	"httpStatus\"\x13\n" +
	"\x11GetProfileRequest\"h\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x1a\n" +
	"\x18ListSharedVolumesRequest\"P\n" +
	"\x19ListSharedVolumesResponse\x123\n" +
	"\avolumes\x18\x01 \x03(\v2\x19.magicbox.v1.SharedVolumeR\avolumes\":\n" +
	"\fSharedVolume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06access\x18\x02 \x01(\tR\x06access\"f\n" +
	"\x14SendToContactRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"X\n" +
	"\x15SendToContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\"\x15\n" +
	"\x13ListContactsRequest\"H\n" +
	"\x14ListContactsResponse\x120\n" +
	"\bcontacts\x18\x01 \x03(\v2\x14.magicbox.v1.ContactR\bcontacts\"Z\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tmultiaddr\x18\x03 \x01(\tR\tmultiaddr2\xbe\x03\n" +
	"\n" +
	"MagicboxOS\x12P\n" +
	"\vSendWebhook\x12\x1f.magicbox.v1.SendWebhookRequest\x1a .magicbox.v1.SendWebhookResponse\x12M\n" +
	"\n" +
	"GetProfile\x12\x1e.magicbox.v1.GetProfileRequest\x1a\x1f.magicbox.v1.GetProfileResponse\x12b\n" +
	"\x11ListSharedVolumes\x12%.magicbox.v1.ListSharedVolumesRequest\x1a&.magicbox.v1.ListSharedVolumesResponse\x12V\n" +
	"\rSendToContact\x12!.magicbox.v1.SendToContactRequest\x1a\".magicbox.v1.SendToContactResponse\x12S\n" +
	"\fListContacts\x12 .magicbox.v1.ListContactsRequest\x1a!.magicbox.v1.ListContactsResponseB2Z0github.com/magicbox/core/api/proto/v1;magicboxpbb\x06proto3"

var (
	file_api_proto_v1_magicbox_proto_rawDescOnce sync.Once
	file_api_proto_v1_magicbox_proto_rawDescData []byte
)

func file_api_proto_v1_magicbox_proto_rawDescGZIP() []byte {
	file_api_proto_v1_magicbox_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_magicbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_magicbox_proto_rawDesc), len(file_api_proto_v1_magicbox_proto_rawDesc)))
	})
	return file_api_proto_v1_magicbox_proto_rawDescData
}

var file_api_proto_v1_magicbox_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_v1_magicbox_proto_goTypes = []any{
	(*SendWebhookRequest)(nil),        // 0: magicbox.v1.SendWebhookRequest
	(*SendWebhookResponse)(nil),       // 1: magicbox.v1.SendWebhookResponse
	(*GetProfileRequest)(nil),         // 2: magicbox.v1.GetProfileRequest
	(*GetProfileResponse)(nil),        // 3: magicbox.v1.GetProfileResponse
	(*ListSharedVolumesRequest)(nil),  // 4: magicbox.v1.ListSharedVolumesRequest
	(*ListSharedVolumesResponse)(nil), // 5: magicbox.v1.ListSharedVolumesResponse
	(*SharedVolume)(nil),              // 6: magicbox.v1.SharedVolume
	(*SendToContactRequest)(nil),      // 7: magicbox.v1.SendToContactRequest
	(*SendToContactResponse)(nil),     // 8: magicbox.v1.SendToContactResponse
	(*ListContactsRequest)(nil),       // 9: magicbox.v1.ListContactsRequest
	(*ListContactsResponse)(nil),      // 10: magicbox.v1.ListContactsResponse
	(*Contact)(nil),                   // 11: magicbox.v1.Contact
}
var file_api_proto_v1_magicbox_proto_depIdxs = []int32{
	6,  // 0: magicbox.v1.ListSharedVolumesResponse.volumes:type_name -> magicbox.v1.SharedVolume
	11, // 1: magicbox.v1.ListContactsResponse.contacts:type_name -> magicbox.v1.Contact
	0,  // 2: magicbox.v1.MagicboxOS.SendWebhook:input_type -> magicbox.v1.SendWebhookRequest
	2,  // 3: magicbox.v1.MagicboxOS.GetProfile:input_type -> magicbox.v1.GetProfileRequest
	4,  // 4: magicbox.v1.MagicboxOS.ListSharedVolumes:input_type -> magicbox.v1.ListSharedVolumesRequest
	7,  // 5: magicbox.v1.MagicboxOS.SendToContact:input_type -> magicbox.v1.SendToContactRequest
	9,  // 6: magicbox.v1.MagicboxOS.ListContacts:input_type -> magicbox.v1.ListContactsRequest
	1,  // 7: magicbox.v1.MagicboxOS.SendWebhook:output_type -> magicbox.v1.SendWebhookResponse
	3,  // 8: magicbox.v1.MagicboxOS.GetProfile:output_type -> magicbox.v1.GetProfileResponse
	5,  // 9: magicbox.v1.MagicboxOS.ListSharedVolumes:output_type -> magicbox.v1.ListSharedVolumesResponse
	8,  // 10: magicbox.v1.MagicboxOS.SendToContact:output_type -> magicbox.v1.SendToContactResponse
	10, // 11: magicbox.v1.MagicboxOS.ListContacts:output_type -> magicbox.v1.ListContactsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_magicbox_proto_init() }
func file_api_proto_v1_magicbox_proto_init() {
	if File_api_proto_v1_magicbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_magicbox_proto_rawDesc), len(file_api_proto_v1_magicbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_magicbox_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_magicbox_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_magicbox_proto_msgTypes,
	}.Build()
	File_api_proto_v1_magicbox_proto = out.File
	file_api_proto_v1_magicbox_proto_goTypes = nil
	file_api_proto_v1_magicbox_proto_depIdxs = nil
}
